vich_uploader:
    db_driver: orm

    mappings:
       pays:
           uri_prefix: /img/pays
           upload_destination: '%kernel.project_dir%/public/img/pays'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
       theme:
           uri_prefix: /img/themes
           upload_destination: '%kernel.project_dir%/public/img/themes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
       avatar:
           uri_prefix: /img/avatar
           upload_destination: '%kernel.project_dir%/public/img/avatar'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
